site_name: Awesome DevOps
site_url: http://awesome-devops.xyz
site_description: A curated list of awesome DevOps platforms, tools, practices and resources
site_author: Marius Stanca
repo_name: awesome-devops Github
repo_url: http://github.com/wmariuss/awesome-devops
edit_uri: https://github.com/wmariuss/awesome-devops/blob/master/README.md

# Copyright
copyright: "Copyright &copy; Awesome DevOps Community"

theme:
  name: material
  language: en
  locale: en
  font: false
  palette:
    primary: black
    accent: blue
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - search.suggest
    - search.highlight

extra:
  feature:
    tabs: true
  font:
    text: Roboto Slab
    code: Source Code Pro
  social:
    - icon: fontawesome/solid/globe
      link: http://marius.xyz
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wmariuss
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wmariuss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wmariuss

extra_css:
  - stylesheets/syntax.css
  - stylesheets/fonts.css

extra_javascript:
  - javascripts/syntax.js

plugins:
  - search:
      lang: en

nav:
  - Welcome: "index.md"
  - List: "list.md"
  - Contribution: "contribution.md"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
